### PR TITLE
fix: bug with no build found 

### PR DESCRIPTION
**Pull request by alikhil**
There is a problem that drone plugin returns error if it does not find last successful build for given branch in last build page.

In this PR I've tried to fix it by adding loop to iterate through all build history

### CODE REVIEW

**Comment by tphoney** [comment]
@alikhil closing and re-opening to trigger ci

**Comment by alikhil** [comment]
@tphoney CI seems broken?

**Comment by tphoney** [comment]
looking now

**Comment by tphoney** [comment]
It ran fine on my new PR.  https://cloud.drone.io/drone-plugins/drone-downstream/80
It looks like your rebase of master didnt go as expected.

**Comment by alikhil** [comment]
@tphoney seems good now. I had to rebase it in cloned repo to make it work

**Comment by tphoney** [comment]
thanks for the hard work ! PR looks great. merging now

**Review by tphoney — APPROVED** [review]

**Pull request merged**
