### PR TITLE
Update drone client to v1.x

### LINKED ISSUE #59: Branch / build no is ignored
The latest `develop` branch build has a number 3. 

First of all, when I did not have a build on master it was

```
time="2019-04-17T09:14:09Z" level=fatal msg="Error: unable to get latest build for owner/repo-name@develop.\n"
```

I created a build on `master` branch, it got number 4.

Then I try both

```yml
kind: pipeline
name: default

steps:
  - name: name
    when:
      branch:
        - master
        - develop
    image: plugins/downstream
    settings:
      server: https://drone.example.com
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - owner/repo-name@develop
```

```
Starting new build 5 for owner/repo-name@develop.
```

and 

```yml
kind: pipeline
name: default

steps:
  - name: name
    when:
      branch:
        - master
        - develop
    image: plugins/downstream
    settings:
      server: https://drone.example.com
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - owner/repo-name@3
```

```
Starting new build 6 for owner/repo-name@3.
```

But both trigger the master build and not develop. So, I assume the @3 and @develop is simply ignored

### PR DESCRIPTION
**Pull request by rohit-smpx**
The current drone client is very old. It breaks when running with drone v1.x.

- Upgraded client
- Changed function calls and variables used from Build object
- Remove fork as it is no longer supported in the client

This might fix #59

### CODE REVIEW

**Comment by rohit-smpx** [comment]
If someone wants to test using this branch, an image is published on docker hub: https://hub.docker.com/r/smartprix/drone-downstream

**Comment by tboerger** [comment]
I'm not sure how to handle that change, this will break Drone setups for <1.0.0

**Comment by rohit-smpx** [comment]
> I'm not sure how to handle that change, this will break Drone setups for <1.0.0

We could publish this with a different tag? Once adoption has increased, could move old release to a legacy tag and make this the latest.
Any idea how other plugins are handling migrating to v1.?

**Comment by tboerger** [comment]
> Any idea how other plugins are handling migrating to v1.?

There are simply not much other plugins using the Drone API directly :)

**Comment by tboerger** [comment]
@drone-plugins/maintainers please give it another review, after that I would merge it and tag it as v2.0.0 as the latest master branch is already tagged as v1.2.0.

**Pull request merged**
