### PR TITLE
Support for build params

### PR DESCRIPTION
**Pull request by jesselang**
Updated `drone-go` to support build parameters, while stopping short of removal of supporting the `fork` parameter. Supports params in KEY=value format as well as loading of params from `godotenv` files.

Example:
```
validate:
  image: plugins/downstream
  server: https://drone.example.com
  params:
    - SOURCE_HASH=${DRONE_COMMIT_HASH}
    - FOO=bar
    - /path/to/godotenv/file
  repositories:
    - octocat/Hello-World
  secrets: [ downstream_token ]
```
I believe this implements the first part of #29.

### CODE REVIEW

**Comment by tboerger** [comment]
So it doesn't support secrets?

**Comment by jesselang** [comment]
I don't currently have a need to support secrets, but I could certainly see that someone might. I appreciate having parameter values displayed in the log when builds are triggered. Perhaps I'll have the plugin caller specify a list of secrets that should be picked up from the environment.

Is there a use case for parameters (not secrets) to be picked up from the environment?

```
validate:
  image: plugins/downstream
  server: https://drone.example.com
  params: # would show up in the log when builds are triggered
    - SOURCE_HASH=${DRONE_COMMIT_HASH}
    - FOO=bar
    - SHELL # is there a use case for parameters to be picked up off the environment? Unclear to me.
    - /path/to/godotenv/file
  secrets: # picked up off the environment, not shown in the log when builds are triggered
    - DOWNSTREAM_TOKEN
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
    - /path/to/godotenv/secrets/file
  repositories:
    - octocat/Hello-World
  secrets: [ downstream_token ]
```

**Comment by jesselang** [comment]
Oops, `secrets` is reserved by Drone to specify which secrets should be injected into the environment. I'm guessing that list isn't accessible to the plugin. Maybe `secret_params` would suffice instead.

**Comment by tboerger** [comment]
For the docker plugin we got build args from secrets realized via `build_args_from_env` which is the addition to `build_args`, for reference: https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker/main.go#L144-L148

**Comment by jesselang** [comment]
I've added support for secrets with `params_from_env`. I would appreciate another review. Thanks!

**Comment by jesselang** [comment]
I have another change I would like to PR which is aptly based on this change. When might this change be merged? Thanks!

**Comment by jesselang** [comment]
Hey @tboerger, could you shed some light on what the end-to-end process is for pull requests to be considered, reviewed, and eventually merged? The process feels a little opaque to me. Thank you.

**Comment by tboerger** [comment]
I would like to get at least one more review.

/cc @drone-plugins/maintainers

**Comment by mrueg** [comment]
Friendly ping :) Would be great to see this included.

**Comment by JohnRoesler** [comment]
I would also like to see this

**Pull request merged**
