### PR TITLE
Replace govendor with dep

### PR DESCRIPTION
**Pull request by jesselang**
I'm working on some changes that require a newer version of the `drone-go` client library. I'm not very familiar with dependency tools that predate `dep`, so I figured that switching to `dep` would benefit me and might also be considered a good housekeeping task.

This should be a one-to-one replacement for the dependencies that are currently in `vendor/vendor.json`. In the event this PR is not merged, can you confirm what tool is being used for dependencies? Looks like https://github.com/kardianos/govendor, but I'm not sure. Thanks!

### CODE REVIEW

**Comment by tboerger** [comment]
Yes we are using govendor so far. Adding vendor to gitignore acts against the structure we got for all plugins. We have added it intentional, some dependent library had been deleted for some plugins and we had not been able to build it anymore. That's why we always keep all sources as part of the repo to keep the builds always reproducible.

**Comment by jesselang** [comment]
Thanks for the context. I've rebased to update the vendored sources using `dep ensure`. Is a move to `dep` advantageous, or should I abandon this and use `govendor` instead? Thanks!

**Comment by metalmatze** [comment]
I think moving to dep is something that is going to be inevitable. But we should decide to move to it with all plugins almost at the same time. Having different vendoring tools across this organization only makes it harder.

**Comment by jesselang** [comment]
Fair enough.

**Pull request closed without merging**
